site_name: Transgov Ghana api documentation
pages:
    - Home: index.md
    - Account_registration: account_registration.md
    - Developmental_Project: developmental_project.md
    - Developmental_Project_v2: developmental_project_v2.0.md
    - Events: transgov_events.md
    - Report_case: report_case.md
    - Update_profile: update_profile.md

theme: readthedocs
