site_name: Transgov Ghana api documentation
pages:
    - Home: index.md
    - 'Account Registration': account_registration.md
    - 'Developmental Project': developmental_project.md
    - 'Developmental Project v2': developmental_project_v2.0.md
    - Events: transgov_events.md
    - 'Report case': report_case.md
    - 'Update fcm_id': update_fcm_id.md
    - 'Update profile': update_profile.md
    - 'Update user account info': update_user_account.md

theme: readthedocs
